### ISSUE TITLE
Licensing update

### ISSUE THREAD

**Issue by libertyernie** [soopercool101/BrawlCrate#82]
Do you know if the code prior to when I took over BrawlBox was MIT licensed? I don't remember there being a license file. I think I made my own code available under MIT (if not, then I'll do so now) but I can't speak to anyone who worked on it before me.

**Comment by soopercool101** [comment]
Odd, I thought I took the license directly from BrawlBox. Looking through it now I may have taken the BrawlManagers license by mistake. I'll remove the license and move it to the code that it explicitly covers

**Comment by soopercool101** [comment]
It appears Brawltools 1 and 2 were actually licensed under LGPL-3. Will change the main license to this accordingly
https://code.google.com/archive/p/brawltools/
https://code.google.com/archive/p/brawltools2/
https://www.gnu.org/licenses/lgpl-3.0.html

**Comment by soopercool101** [comment]
Let me know if there are any considerations you want me to take for your code in particular since your repo doesn't currently have a license. I realize I was somewhat cavalier with how this project started but I certainly do not want to do anything against the wishes of those whose work this project is fundamentally built on

**Comment by libertyernie** [comment]
I updated my repo to say that my own contributions are available as either MIT No Attribution or LGPL 3+, and also linked to yours. So it sounds like it's safe to say LGPL 3+ covers everything. I never realized Google Code had a field for license, so it's no wonder it didn't make it into my fork.
